# Site settings
title: MyIsmin
email: mathieu@rousse.me
description: Site internet des associations du campus Georges Charpak Provence des Mines de St Etienne. Tu veux savoir ce qu'on fait ? Come in !
baseurl: "/MyIsmin/" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site
twitter_username: roussemath
github_username:  m-rousse
permalink: /:title.html

# Build settings
markdown: kramdown
